// PDF Export utility for generating heritage risk assessment reports
// Uses browser's print functionality for PDF generation

import type { RiskAssessmentReport, ComparativeAnalysis } from '../services/ReportService';

/**
 * PDF Export utility for heritage risk assessment reports
 * In production, consider using libraries like jsPDF or Puppeteer for more control
 */
export class PDFExport {
  
  /**
   * Export report to PDF using browser print functionality
   * @param report Report data to export
   * @param filename Desired filename for the PDF
   */
  static exportToPDF(
    report: RiskAssessmentReport | ComparativeAnalysis, 
    filename: string = 'heritage-risk-report.pdf'
  ): void {
    // Create a new window for printing
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to generate PDF reports');
      return;
    }

    // Generate HTML content for the report
    const htmlContent = this.generateReportHTML(report);
    
    // Write content to the new window
    printWindow.document.write(htmlContent);
    printWindow.document.close();

    // Wait for content to load, then trigger print
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
        // Close the window after printing (user can cancel)
        printWindow.onafterprint = () => {
          printWindow.close();
        };
      }, 250);
    };
  }

  /**
   * Generate HTML content for the report
   * @param report Report data
   * @returns HTML string for printing
   */
  private static generateReportHTML(report: RiskAssessmentReport | ComparativeAnalysis): string {
    const isComparative = 'riskComparison' in report;
    
    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>${isComparative ? 'Heritage Sites Comparative Analysis' : `Heritage Risk Report - ${(report as RiskAssessmentReport).site?.name}`}</title>
          <style>
            ${this.getPrintStyles()}
          </style>
        </head>
        <body>
          ${isComparative ? this.generateComparativeHTML(report as ComparativeAnalysis) : this.generateStandardHTML(report as RiskAssessmentReport)}
        </body>
      </html>
    `;
  }

  /**
   * Generate HTML for standard site report
   */
  private static generateStandardHTML(report: RiskAssessmentReport): string {
    return `
      <div class="report-container">
        <header class="report-header">
          <h1>Heritage Risk Assessment Report</h1>
          <h2>${report.site.name}</h2>
          <div class="report-meta">
            <p><strong>Location:</strong> ${report.site.location.address}</p>
            <p><strong>Generated:</strong> ${report.generatedAt.toLocaleDateString()}</p>
            <p><strong>Generated by:</strong> ${report.generatedBy}</p>
            <p><strong>Report Type:</strong> ${report.reportType.replace('-', ' ').toUpperCase()}</p>
          </div>
        </header>

        <section class="executive-summary">
          <h3>Executive Summary</h3>
          <div class="summary-stats">
            <div class="stat-item">
              <span class="stat-label">Total Threats:</span>
              <span class="stat-value">${report.summary.totalThreats}</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Highest Risk:</span>
              <span class="stat-value risk-${report.summary.highestRisk}">${report.summary.highestRisk.replace('-', ' ').toUpperCase()}</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Average Magnitude:</span>
              <span class="stat-value">${report.summary.averageMagnitude}</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Urgent Actions:</span>
              <span class="stat-value">${report.summary.urgentActions}</span>
            </div>
          </div>
        </section>

        <section class="site-description">
          <h3>Site Description</h3>
          <p>${report.site.description}</p>
          
          <h4>Historical Significance</h4>
          <p>${report.site.significance}</p>
          
          <div class="site-status">
            <p><strong>Current Status:</strong> <span class="status-${report.site.currentStatus}">${report.site.currentStatus.replace('-', ' ').toUpperCase()}</span></p>
            <p><strong>Last Assessment:</strong> ${new Date(report.site.lastAssessment).toLocaleDateString()}</p>
          </div>
        </section>

        <section class="recommendations">
          <h3>Key Recommendations</h3>
          <ol>
            ${report.recommendations.map(rec => `<li>${rec}</li>`).join('')}
          </ol>
        </section>

        <section class="risk-assessments">
          <h3>Detailed Risk Assessments</h3>
          <p class="methodology-note">Following ABC Scale methodology: A=Probability, B=Loss of Value, C=Fraction Affected</p>
          
          <table class="assessments-table">
            <thead>
              <tr>
                <th>Threat Type</th>
                <th>Priority</th>
                <th>A</th>
                <th>B</th>
                <th>C</th>
                <th>Magnitude</th>
                <th>Uncertainty</th>
                <th>Assessment Date</th>
                <th>Assessor</th>
              </tr>
            </thead>
            <tbody>
              ${report.assessments.map(assessment => `
                <tr>
                  <td>${assessment.threatType.replace('-', ' ').replace(/\b\w/g, l => l.toUpperCase())}</td>
                  <td class="priority-${assessment.priority}">${assessment.priority.replace('-', ' ').toUpperCase()}</td>
                  <td>${assessment.probability}</td>
                  <td>${assessment.lossOfValue}</td>
                  <td>${assessment.fractionAffected}</td>
                  <td><strong>${assessment.magnitude}</strong></td>
                  <td>${assessment.uncertaintyLevel.toUpperCase()}</td>
                  <td>${new Date(assessment.assessmentDate).toLocaleDateString()}</td>
                  <td>${assessment.assessor}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </section>

        <footer class="report-footer">
          <p>This report follows ICCROM Heritage Risk Assessment Guidelines</p>
          <p>Generated by Heritage Guardian System on ${new Date().toLocaleDateString()}</p>
        </footer>
      </div>
    `;
  }

  /**
   * Generate HTML for comparative analysis report
   */
  private static generateComparativeHTML(report: ComparativeAnalysis): string {
    return `
      <div class="report-container">
        <header class="report-header">
          <h1>Heritage Sites Comparative Analysis</h1>
          <div class="report-meta">
            <p><strong>Sites Analyzed:</strong> ${report.sites.length}</p>
            <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
          </div>
        </header>

        <section class="comparative-overview">
          <h3>Risk Comparison Summary</h3>
          <table class="comparison-table">
            <thead>
              <tr>
                <th>Site Name</th>
                <th>Location</th>
                <th>Overall Risk</th>
                <th>Total Assessments</th>
                <th>Average Magnitude</th>
                <th>Urgent Threats</th>
              </tr>
            </thead>
            <tbody>
              ${report.riskComparison.map(site => `
                <tr>
                  <td><strong>${site.siteName}</strong></td>
                  <td>${report.sites.find(s => s.id === site.siteId)?.location.address || 'N/A'}</td>
                  <td class="risk-${site.overallRisk}">${site.overallRisk.replace('-', ' ').toUpperCase()}</td>
                  <td>${site.totalAssessments}</td>
                  <td>${site.averageMagnitude}</td>
                  <td>${site.urgentThreats}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </section>

        <section class="regional-trends">
          <h3>Regional Trends</h3>
          ${report.regionalTrends.map(trend => `
            <div class="trend-item">
              <h4>${trend.country}</h4>
              <p><strong>Average Risk Level:</strong> ${trend.averageRisk}</p>
              <p><strong>Common Threats:</strong> ${trend.commonThreats.map(t => t.replace('-', ' ').replace(/\b\w/g, l => l.toUpperCase())).join(', ')}</p>
            </div>
          `).join('')}
        </section>

        <footer class="report-footer">
          <p>This comparative analysis follows international heritage risk assessment standards</p>
          <p>Generated by Heritage Guardian System on ${new Date().toLocaleDateString()}</p>
        </footer>
      </div>
    `;
  }

  /**
   * Get CSS styles for print layout
   */
  private static getPrintStyles(): string {
    return `
      @page {
        margin: 1in;
        size: A4;
      }

      * {
        box-sizing: border-box;
      }

      body {
        font-family: 'Times New Roman', serif;
        font-size: 12pt;
        line-height: 1.4;
        color: #000;
        margin: 0;
        padding: 0;
      }

      .report-container {
        max-width: 100%;
        margin: 0 auto;
      }

      .report-header {
        text-align: center;
        margin-bottom: 30px;
        padding-bottom: 20px;
        border-bottom: 2px solid #333;
      }

      .report-header h1 {
        font-size: 18pt;
        font-weight: bold;
        margin: 0 0 10px 0;
        color: #2c3e50;
      }

      .report-header h2 {
        font-size: 16pt;
        font-weight: bold;
        margin: 0 0 15px 0;
        color: #34495e;
      }

      .report-meta {
        text-align: left;
        margin-top: 15px;
      }

      .report-meta p {
        margin: 5px 0;
        font-size: 11pt;
      }

      h3 {
        font-size: 14pt;
        font-weight: bold;
        color: #2c3e50;
        margin: 25px 0 15px 0;
        border-bottom: 1px solid #bdc3c7;
        padding-bottom: 5px;
      }

      h4 {
        font-size: 12pt;
        font-weight: bold;
        color: #34495e;
        margin: 20px 0 10px 0;
      }

      p {
        margin: 10px 0;
        text-align: justify;
      }

      .summary-stats {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 15px;
        margin: 20px 0;
      }

      .stat-item {
        display: flex;
        justify-content: space-between;
        padding: 10px;
        border: 1px solid #bdc3c7;
        border-radius: 4px;
      }

      .stat-label {
        font-weight: bold;
      }

      .stat-value {
        font-weight: bold;
      }

      .risk-extremely-high { color: #dc3545; }
      .risk-very-high { color: #ff6b35; }
      .risk-high { color: #ffc107; }
      .risk-medium-high { color: #fd7e14; }
      .risk-low { color: #28a745; }

      .status-active { color: #28a745; }
      .status-at-risk { color: #ffc107; }
      .status-critical { color: #dc3545; }
      .status-stable { color: #17a2b8; }

      .recommendations ol {
        padding-left: 20px;
      }

      .recommendations li {
        margin: 8px 0;
        line-height: 1.5;
      }

      .methodology-note {
        font-style: italic;
        color: #666;
        margin-bottom: 15px;
      }

      table {
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
        font-size: 10pt;
      }

      th, td {
        border: 1px solid #bdc3c7;
        padding: 8px;
        text-align: left;
        vertical-align: top;
      }

      th {
        background-color: #ecf0f1;
        font-weight: bold;
        text-align: center;
      }

      .priority-extremely-high { background-color: #ffebee; color: #dc3545; font-weight: bold; }
      .priority-very-high { background-color: #fff3e0; color: #ff6b35; font-weight: bold; }
      .priority-high { background-color: #fffbf0; color: #ffc107; font-weight: bold; }
      .priority-medium-high { background-color: #fff8f0; color: #fd7e14; font-weight: bold; }
      .priority-low { background-color: #f1f8e9; color: #28a745; font-weight: bold; }

      .trend-item {
        margin: 15px 0;
        padding: 15px;
        border: 1px solid #bdc3c7;
        border-radius: 4px;
      }

      .trend-item h4 {
        margin-top: 0;
      }

      .report-footer {
        margin-top: 40px;
        padding-top: 20px;
        border-top: 1px solid #bdc3c7;
        text-align: center;
        font-size: 10pt;
        color: #666;
      }

      .report-footer p {
        margin: 5px 0;
      }

      /* Page break controls */
      .executive-summary,
      .site-description,
      .recommendations,
      .risk-assessments {
        page-break-inside: avoid;
      }

      h3 {
        page-break-after: avoid;
      }

      /* Print-specific adjustments */
      @media print {
        body {
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
        }
        
        .report-container {
          box-shadow: none;
        }
      }
    `;
  }
}